package ca.uqam.info.mgl7460.boutique.domain;

public enum Province {
ALBERTA, 
QUEBEC, 
ONTARIO, 
NEW_BRUNSWICK, 
NOVA_SCOTIA,
NEWFOUNDLAND, 
MANITOBA, 
BRITISH_COLUMBIA, 
PRINCE_EDWARD_ISLAND, 
SASKATCHEWAN,
YUKON,
NORTHWEST_TERRITORIES
}
